services:
  # Serviço da aplicação Node.js
  pdf-tools:
    build: .
    container_name: pdf-tools-v2-app
    volumes:
      - .:/app
      - /app/node_modules
      - ./documents:/app/documents
    shm_size: '2gb'
    environment:
      - NODE_ENV=development
      # [IMPORTANTE] Use o IP da sua máquina Linux na rede local
      - APP_PUBLIC_URL=http://172.18.130.29:81
    restart: always

  # Serviço do Collabora Online
  collabora:
    image: collabora/code:latest
    container_name: pdf-tools-v2-collabora
    ports:
      # --- CORREÇÃO APLICADA ---
      # Expõe a porta 9980 no IP do host, permitindo acesso externo para teste
      # e comunicação interna do Nginx.
      - "9980:9980"
    environment:
      # Esta variável diz ao Collabora para aceitar conexões vindas do seu domínio/IP
      # O curinga '*' é ideal para o desenvolvimento local via IP.
      - aliasgroup1=http://*:81
      # Desabilita o SSL do próprio Collabora, pois o Nginx cuidará disso
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
    restart: always
    cap_add:
      - MKNOD

  # Serviço do Nginx para o ambiente local
  nginx:
    image: nginx:stable-alpine
    container_name: pdf-tools-v2-nginx
    ports:
      - "81:81"
    volumes:
      # Garante que o arquivo .conf correto está sendo montado
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - pdf-tools
      - collabora
    restart: always